spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/compare_karo
  datasource:
    driver-class-name: org.postgresql.Driver
    password:
    url: jdbc:postgresql://localhost:5432/m0a00pf?currentSchema=compare_karo
    username: m0a00pf

cassandra:
  secure-connect-file: /Users/m0a00pf/Downloads/secure-connect-suggest-cars.zip
  client-id:
  client-secret:
  token: 